### ISSUE TITLE
LEDs permissions in sysfs with trigger timer

### ISSUE THREAD

**Issue by JoseGoncalves** [beagleboard/customizations#7]
After changing the trigger in the user LEDs to `timer` the kernel adds two new entries in sysfs, named `delay_on` and `delay_off` and these are owned by root, what invalidates a user from group `gpio` to control those delay values.

I sugest that a udev rule should be setup for changing the permissions, in a similar way to what is currently done for GPIOs. This rule works for me:

```
SUBSYSTEM=="leds", ACTION=="change", \
        RUN+="/bin/chgrp -R gpio '/sys%p'", \
        RUN+="/bin/chmod -R g=u '/sys%p'"
```

**Comment by RobertCNelson** [comment]
thanks @JoseGoncalves!
